name: hello-world

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "Hello, world !"
  test:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: flutter test
